### ISSUE TITLE
Plano de iteração - Release: 1.1.0

### ISSUE THREAD

**Issue by v1d3rm3** [ccsa-ufrn/seminario-ccsa-old#1]
Diretrizes para o lançamento da release 1.1.0.

**IMPORTANTE**: Ao concluir o desenvolvimento de cada uma das issues, por favor, colocar detalhes de cada implementação nas suas respectivas issues, para termos detalhes do desenvolvimento.

- [x] **Criação da API**
    - [x] ~~Endpoint para recuperação de **Notícias**~~ #2 
    - [x] ~~Endpoint para recuperação dos **Grupos de Trabalho**~~ #3
    - [x] ~~Endpoint para envio de mensagem de **Contato**~~ #4
    - [x] ~~Endpoint para cadastrar novo **Usuário**~~ #5
    - [x] ~~Endpoint para a realização de **Login**~~ #6

**Comment by v1d3rm3** [comment]
Alteração do prazo para até **sexta-feira** (17/02) à pedido de Arlete... @mrmorais @marconiccsa
